# Generated by Django 3.2 on 2022-06-12 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gugols', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gugols.category', verbose_name='dd'),
        ),
    ]
