# Generated by Django 3.2 on 2022-04-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gugols', '0002_ourwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendUserAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='publications_images')),
            ],
        ),
    ]
