# Generated by Django 3.2 on 2022-06-21 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gugols', '0002_alter_signin_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gugols.category', verbose_name='Выберите услугу'),
        ),
    ]
