# Generated by Django 3.2 on 2022-04-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gugols', '0003_senduseradmin_workers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='service_images')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AlterModelOptions(
            name='workers',
            options={'verbose_name': 'Наши экперты', 'verbose_name_plural': 'Наши экперты'},
        ),
        migrations.AlterField(
            model_name='workers',
            name='image',
            field=models.ImageField(null=True, upload_to='publication_images'),
        ),
    ]
